import { chromium } from '@playwright/test'
import { mkdir } from 'node:fs/promises'
await mkdir('artifacts', { recursive: true })
const browser = await chromium.launch({ channel: 'chrome', headless: true })
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
const errors = []
page.on('pageerror', error => errors.push(error.message))
page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
page.on('response', response => { if (response.status() >= 400) errors.push(response.status() + ' ' + response.url()) })
await page.goto('http://127.0.0.1:5173/')
await page.waitForTimeout(5000)
await page.screenshot({ path: 'artifacts/after-hero.png' })
await page.evaluate(() => window.scrollTo(0, window.innerHeight))
await page.waitForTimeout(1800)
await page.screenshot({ path: 'artifacts/after-scene.png' })
await page.mouse.move(1250, 220)
await page.waitForTimeout(500)
await page.screenshot({ path: 'artifacts/after-hover.png' })
await page.setViewportSize({ width: 390, height: 844 })
await page.evaluate(() => window.scrollTo(0, window.innerHeight))
await page.waitForTimeout(2000)
await page.screenshot({ path: 'artifacts/after-mobile.png' })
console.log(JSON.stringify({ errors }, null, 2))
await browser.close()
